metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.1.5.210, mac: '90:b1:1c:88:3b:45', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 10.1.5.211, mac: '18:66:da:4c:08:93', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 10.1.5.212, mac: '48:4d:7e:ce:18:4c', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal3: {ansible_host: 10.1.5.213, mac: '48:4d:7e:ce:37:c7', disk: sda, network_interface: eno1}
