metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.1.5.210, mac: '00:23:24:d1:f5:69', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 10.1.5.211, mac: '00:23:24:d1:f3:f0', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 10.1.5.212, mac: '00:23:24:e7:04:60', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal3: {ansible_host: 10.1.5.213, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1}
